name: schoolapp
description: A new Flutter project.
version: 1.0.0+4
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  url_launcher: ^6.2.1
  razorpay_flutter: ^1.3.0
  carousel_slider:
  sticky_headers:
  flutter_inappwebview: ^5.3.2
  upi_payment_qrcode_generator: ^1.4.0
  connectivity: ^3.0.6
  flutter_cached_pdfview: ^0.4.2
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanBold.ttf
          weight: 700
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansRomanSemiBold.ttf
          weight: 600
